config/routes.rb
Rails.application.routes.draw do

  resources :patients
  resources :messages
  resources :results
  resources :posts
  resources :doctors
  devise_for :users
  devise_scope :user do 
    root 'devise/sessions#new'
  end

end

app/models/result.rb
class Result < ActiveRecord::Base
	belongs_to :patient
	belongs_to :doctor
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @patient = Patient.find(params[:patient_id])
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)
    if current_user.doctor == true
      @result.doctor_id = Doctor.where(user_id: current_user.id).first.id
      @result.save
      redirect_to patient_path(@result.patient_id)
    else
      @result.doctor_id = Patient.where(user_id: current_user.id).first.doctor_id
      @result.save
      redirect_to patient_path(@result.patient_id)
    end
  end


  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:doctor_id, :patient_id, :status, :raw_data, :notes)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<h1 class="results-form-title">New Result</h1>

<div class="form">

<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>
      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :status, placeholder: 'Status', class: 'input' %>
  </div>
  <div class="field">
    <%= f.text_field :raw_data, placeholder: 'Upload document here', class: 'input' %>
  </div>
  <div class="field">
    <%= f.text_area :notes, placeholder: 'Additional notes', class: 'input text-input' %>
    <%= f.hidden_field :patient_id, value: @patient.id %>
  </div>
  <div class="submit-button">
    <%= f.submit "Submit", class: 'submit'%>
  </div>
<% end %>

</div>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Results</h1>

<table>
  <thead>
    <tr>
      <th>Doctor</th>
      <th>Patient</th>
      <th>Status</th>
      <th>Raw data</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.doctor_id %></td>
        <td><%= result.patient_id %></td>
        <td><%= result.status %></td>
        <td><%= result.raw_data %></td>
        <td><%= result.notes %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<%= render 'form' %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor:</strong>
  <%= @result.doctor_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @result.patient_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @result.status %>
</p>

<p>
  <strong>Raw data:</strong>
  <%= @result.raw_data %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @result.notes %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>