config/routes.rb
Rails.application.routes.draw do

  resources :patients
  resources :messages
  resources :results
  resources :posts
  resources :doctors
  devise_for :users
  devise_scope :user do 
    root 'devise/sessions#new'
  end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :doctor
	belongs_to :user
	has_many :posts
	has_many :results
	has_many :messages
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @posts = Post.all
    @post = Post.new
    @doctor = Doctor.where(user_id: current_user.id).first.id
    @patients = Patient.where(doctor_id: @doctor)
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @posts = Post.where(patient_id: params[:id]).reverse
    @post = Post.new
    @messages = Message.where(patient_id: params[:id]).reverse
    @message = Message.new
    @results = Result.where(patient_id: params[:id]).reverse
    @result = Result.new
    
    @patient_name = User.where(id: @patient.user_id).first.first_name
    @patient_last_name = User.where(id: @patient.user_id).first.last_name
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:user_id, :doctor_id)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br>
    <%= f.number_field :doctor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Doctors</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.user_id %></td>
        <td><%= patient.doctor_id %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<div class="wrapper">

	<div class="hero">
		<% if current_user.doctor == true %>
			<p>	<br>
				<strong>Patient:</strong>
				<%= @patient_name %> <%= @patient_last_name %>
			</p>

		<%else%>
			<p>	Hello <%= @patient_name %>, you are speaking with your GP, Dr.
				<% @patient = Patient.where(user_id: [current_user.id]).first%>
				<% @doctor = Doctor.where(id: [@patient.doctor_id]).first %>
				<% @doctor_name = User.where(id: [@doctor.user_id]).first.first_name %>
				<% @doctor_last_name = User.where(id: [@doctor.user_id]).first.last_name %>
				<%= @doctor_name %> <%= @doctor_last_name %>
				<br>
				<%= image_tag ('Doctor-790x1024.jpg')%>
			</p>

		<%end%>
	</div>
	<div class="symptoms container">
		  <h3 class="header">Symptoms</h3>
		<% if current_user.doctor == true %>
						<% else %>
			<div class="symptom-input">
					<div class="new-button"><%= link_to 'New Symptom', new_post_path(:patient_id => @patient.id) %>
					</div>
			</div>
		<% end %>
			<div class="info-container">
					<% @posts.each do |post| %>
						<div class="symptom-contents">
							<div class="timestamp">
								<%= post.created_at.strftime("%A at %H:%M%p")  %>
							</div>
							<div class="location">
								<a> Location of Issue: </a><br>
								<p>
									<%= post.location %>
								</p>
							</div>
							<div class="discomfort">
								<a> Level of Discomfort: </a><br>
								<p>
								<%= post.discomfort %>
								</p>
							</div>
							<div class="frequency">
								<a> Frequency: </a><br>
								<p>
									<%= post.frequency %>
								</p>
							</div>
							<div class="initial_occurence">
								<a> Initial Occurence: </a><br>
								<p>
									<%= post.initial_occurence %>
								</p>
							</div>
							<div class="notes">
								<a> Notes: </a><br>
								<%= post.notes %>
							</div>
						</div>
					<%end%>
		</div>
	</div>

	<div class="messages container">
		  <h3>Messages</h3>
		<div class="message-input">
			<%= form_for(@message) do |f| %>

			  <div class="field box">
			    <%= f.text_area :content, :placeholder => "Type your message here..." %>
			  </div>

			  <div class="field">
			    <%= f.hidden_field :patient_id, value: @patient.id %>
			  </div>

			  <div class="actions group">
			    <%= f.submit "Send" %>
			  </div>

			<% end %>
		</div>
		<div class="info-container">
			<% @messages.each do |message| %>
				<div class="message-contents">
					<div class="created_by">
						<% @message_maker = User.where(id: [message.created_by]).first.first_name %>
						<%= @message_maker %>
					</div>
					<div class="content">
						<%= message.content %>
					</div>
					<div class="timestamp">
						<%= message.created_at.strftime("%A at %H:%M%p")  %>
					</div>
				</div>
			<%end%>
		</div>

	</div>

	<div class="results container">
		  <h3>Results</h3>
		<% if current_user.doctor == true %>
			<div class="results-input">
				<%= link_to 'New Result', new_result_path(:patient_id => @patient.id) %>
			</div>
		<% end %>	
		<div class="info-container">
			<% @results.each do |result| %>
				<div class="results-contents">
					<div class="timestamp">
						<%= result.created_at.strftime("%A at %H:%M%p")  %>
					</div>
					<div class="status">
						<a> Summary of Results: </a><br>
						<%= result.status %>
					</div>
					<div class="raw_data">
						<a> Data: </a><br>
				
							<%= link_to "http://www.beatcfsandfms.org/GeorgesTests/OrganicAnal_1098_pg1.gif",class: 'attachment' do %>
							<%= image_tag('attachment', class: 'attachment') %>

							<%end%>

					
					</div>
					<div class="notes">
						<a> Doctors notes: </a><br>
						<%= result.notes %>
					</div>
				</div>
			<%end%>	
		</div>
	</div>

</div>